version: '3.8'

# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-sfi-payment-submission:
    build:
      target: development
    image: ffc-sfi-payment-submission-development
    container_name: ffc-sfi-payment-submission-development
    ports:
      - "9243:9229"
    volumes:
      - ./app/:/home/node/app/
      - ./package.json:/home/node/package.json
    environment:
      AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://ffc-sfi-payment-submission-azurite:10000/devstoreaccount1;

  ffc-sfi-payment-submission-postgres:
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ffc-sfi-payment-submission-azurite:
    volumes:
      - azurite_data:/data
    ports:
      - "10001:10000"

volumes:
  azurite_data:
  postgres_data:

